
---

log:
  version: 1
  disable_existing_loggers: false
  handlers:
    stderr:
      class: logging.StreamHandler
      stream: ext://sys.stderr
      level: DEBUG

  loggers:
    main:
      level: DEBUG
      handlers: [stderr]
    cogs:
      level: INFO
      handlers: [stderr]


