
---

log:
  version: 1
  disable_existing_loggers: false
  handlers:
    stderr:
      class: logging.StreamHandler
      stream: ext://sys.stderr
      level: WARNING
    stdout:
      class: logging.StreamHandler
      stream: ext://sys.stdout
      level: DEBUG

  loggers:
    launcher:
      level: DEBUG
      handlers: [stderr, stdout]
    cogs:
      level: INFO
      handlers: [stderr]


