---
name: Documentations

on:
  pull_request:

jobs:
  test-i18n:
    name: Check i18n Coverage
    runs-on: ubuntu-latest
    outputs:
      pouet: "toto"

    steps:
      - uses: actions/checkout@v2

      - name: Check i18n coverage
        id: i18nCoverage
        uses: alexkiro/i18n-coverage@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          translations-path: 'locales/**/LC_MESSAGES/*.po'

      - name: Check i18n coverage Documentation
        id: i18nCoverageDoc
        uses: alexkiro/i18n-coverage@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          translations-path: 'docs/locales/**/LC_MESSAGES/*.po'

