---
name: Documentations

on:
  pull_request:

jobs:
  i18nCoverage:
    name: Check i18n Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check i18n coverage
        id: i18nCoverage
        uses: alexkiro/i18n-coverage@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          translations-path: 'locales/**/LC_MESSAGES/*.po'

  i18nDocsCoverage:
    name: Check i18n Documentation Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check i18n coverage Documentation
        id: i18nCoverageDoc
        uses: alexkiro/i18n-coverage@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          translations-path: 'docs/locales/**/LC_MESSAGES/*.po'