# Lint test run on PR
# but should not run after push to master because reporting
# these after push is meaningless to the building of the package
name: Test Lint

on:
  pull_request:

jobs:
  test-lint:
    runs-on: ubuntu-latest
    name: Test Lint
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

#echo "::group::My title"
#echo "Inside group"
#echo "::endgroup::"

    - name: Install dependencies
      run: |
        echo "::group::Pip install"
        python -m pip install --upgrade pip setuptools wheel
        echo "::endgroup::"
        echo "::group::install virtualenv tox tox-gh-actions"
        pip install virtualenv tox tox-gh-actions
        echo "::endgroup::"

    - name: Lint
      run: tox -e lint

    - name: Radon
      run: tox -e radon
