---
name: Test Python

on:
  pull_request:
#  push:
#    branches:
#      - main
#      - dev
#      - test
#      - tox

jobs:
  test-py:
    runs-on: ${{ matrix.platform }}
    name: Test Python
    strategy:
      matrix:
#        platform: [ubuntu-latest, macos-latest, windows-latest]
#        python-version: [3.6, 3.7, 3.8]
        platform: [ubuntu-latest]
        python-version: [3.7]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          echo "::group::Pip install"
          python -m pip install --upgrade pip setuptools wheel
          echo "::endgroup::"
          echo "::group::install coverage[toml] virtualenv tox tox-gh-actions"
          pip install coverage[toml] virtualenv tox tox-gh-actions
          echo "::endgroup::"

      - name: Test with tox
        run: tox

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          verbose: true
          files: ./coverage.xml
          fail_ci_if_error: true